export const ON_PRODUCT_CLICKED = 'ON_PRODUCT_CLICKED';
export const ON_COMPARE_CLICKED = 'ON_COMPARE_CLICKED';
export const ON_COMPARE_CLEAR_CLICKED = 'ON_COMPARE_CLEAR_CLICKED';
export const ON_INSURANCE_PROVIDER_FILTER = 'ON_INSURANCE_PROVIDER_FILTER';
export const ON_SERVICE_AREA_IDS_FILTER = 'ON_SERVICE_AREA_IDS_FILTER';

export const ON_SORT_PREMIUM = 'ON_SORT_PREMIUM';
export const ON_SORT_CREATEDAT = 'ON_SORT_CREATEDAT';